// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnlgjpnvtqsbwjkbflvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJubGdqcG52dHFzYndqa2JmbHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjA3NjgsImV4cCI6MjA2NjYzNjc2OH0.D3NrUbenAi_fhH1dNxAJQQ1iPvoSxGhwnjV_bDA_btI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});